"""crear tabla mascotas

Revision ID: 2adcaa123325
Revises: f5d7370c69d5
Create Date: 2026-07-14 09:24:39.682638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adcaa123325'
down_revision: Union[str, None] = 'f5d7370c69d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas',
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('dni_propietario', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dni_propietario'], ['clientes.dni'], ),
    sa.PrimaryKeyConstraint('id_mascota')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    # ### end Alembic commands ###
